apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: app-sts
  namespace: app
spec:
  serviceName: app-sts-svc
  replicas: 2
  selector:
    matchLabels:
      app: app-sts
  template:
    metadata:
      labels:
        app: app-sts
    spec:
      containers:
        - name: app
          image: 000000000000.dkr.ecr.ap-northeast-2.amazonaws.com/skills-app:v1.0.0
          ports:
            - name: http
              containerPort: 8080
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: ["ReadWriteOnce"]
        storageClassName: ebs-gp3
        resources:
          requests:
            storage: 10Gi
